#!/usr/bin/env python
#coding=utf8
__project__ = 'zbxha'
__author__ = 'liugl'
__date__ = '08/12/2015'
import sys,getopt
import os,time,ConfigParser,logging,commands
from logging.handlers import TimedRotatingFileHandler
import paramiko

class Logger():
    def __init__(self, path,  Flevel=None, Slevel=None):
        self.logger = logging.getLogger(path)
        self.logger.setLevel(logging.DEBUG)
        fmt = logging.Formatter('[%(asctime)s] %(levelname)-8s %(message)s', '%Y-%m-%d %H:%M:%S')
        if Flevel:
            fh = logging.FileHandler(path)
            # fh = TimedRotatingFileHandler(path, 'midnight', 1, 4)
            # fh.suffix = '%Y-%m-%d_%H:%M:%S.log'
            fh.setFormatter(fmt)
            fh.setLevel(Flevel)
            self.logger.addHandler(fh)
        if Slevel:
            sh = logging.StreamHandler()
            sh.setFormatter(fmt)
            sh.setLevel(Slevel)
            self.logger.addHandler(sh)

    def debug(self,message):
        self.logger.debug(message)

    def info(self,message):
        self.logger.info(message)

    def warning(self,message):
        self.logger.warning(message)

    def error(self,message):
        self.logger.error(message)

    def critical(self,message):
        self.logger.critical(message)

class ssh():
    def __init__(self, hostname, port, username, password=None, key_filename=None, timeout=5):
        self.hostname = hostname
        self.port = port
        self.username = username
        self.password = password
        self.key_filename = key_filename
        self.timeout= timeout
        self.client = None
        self.connect()

    def connect(self):
        if self.client is None:
            self.client = paramiko.SSHClient()
            self.client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            self.client.connect(self.hostname, self.port, self.username, self.password, key_filename=self.key_filename, timeout=self.timeout)

    def exec_command(self, cmd):
        self.connect()
        stdin, stdout, stderr = self.client.exec_command(cmd)
        message = stdout.readlines()
        error   = stderr.readlines()
        if len(error) > 0:
            result = False
            msg = error
        else:
            result = True
            msg = message
        return result, msg

    def upload(self, localpath, remotepath):
        self.connect()
        sftp = self.client.open_sftp()
        sftp.put(localpath, remotepath)

    def download(self, remotepath, localpath):
        self.connect()
        sftp = self.client.open_sftp()
        sftp.get(remotepath, localpath)

    def close(self):
        self.client.close()

class CheckZabbixServer():
    def __init__(self, serverip, gateway, senderhost, key, value, port=10051, zbxsender='/usr/bin/zabbix_sender '):
        self.serverip = serverip
        self.gateway = gateway
        self.senderhost = senderhost
        self.key = key
        self.value = value
        self.port = port
        self.zbxsender = zbxsender

    def fpinggateway(self):
        status, output = commands.getstatusoutput('/usr/sbin/fping ' + self.gateway)
        if status > 0:
            return False
        else:
            return True

    def fpingzbx(self):
        status, output = commands.getstatusoutput('/usr/sbin/fping ' + self.serverip)
        if status > 0:
            return False
        else:
            return True

    def zabbix_sender(self):
        cmd = "%s -z %s -s %s -k %s -o %s" %(self.zbxsender, self.serverip, self.senderhost, self.key, self.value)
        status, output = commands.getstatusoutput(cmd)
        if status > 0:
            return False
        else:
            return True

class RecoveryZabbixServer():
    def __init__(self, serviceip, netmask, device, gateway, conn):
        self.serviceip = serviceip
        self.netmask = netmask
        self.device = device
        self.gateway = gateway
        self.conn = conn

    def checkip(self):
        result, msg = self.conn.exec_command('sudo /sbin/ip addr | grep %s' %(self.serviceip))
        if result:
            try:
                if self.serviceip in msg[0]:
                    return True
            except:
                return False
        else:
            return False

    def addip(self):
        result, msg = self.conn.exec_command('sudo /sbin/ip addr add %s/%s dev %s' %(self.serviceip, self.netmask, self.device))
        if result:
            if bool(msg):  # return error message
                return False
            else:  # not message is best message
                result, msg = self.conn.exec_command('sudo /sbin/arping -c 2 -I %s -s %s %s' %(self.device, self.serviceip, self.gateway))
                return True
        else:
            return False

    def delip(self):
        result, msg = self.conn.exec_command('sudo /sbin/ip addr del %s/%s dev %s' %(self.serviceip, self.netmask, self.device))
        if bool(msg):  # return error message
            return False
        else:  # not message is best message
            return True

    def checkzbx(self):
        result, msg = self.conn.exec_command('sudo /etc/init.d/zabbix-server status')
        if 'running' in msg[0]:
            return True
        elif 'stopped' in msg[0] or 'dead':
            return False

    def startzbx(self):
        result, msg = self.conn.exec_command('sudo /etc/init.d/zabbix-server start')
        time.sleep(10)
        if self.checkzbx():
            return True
        else:
            return False

    def stopzbx(self):
        result, msg = self.conn.exec_command('sudo /etc/init.d/zabbix-server stop')
        time.sleep(10)
        if self.checkzbx():
            return False
        else:
            return True

def createDaemon():
    # create - fork 1
    try:
        if os.fork() > 0:
            os._exit(0)
    except OSError, error:
        print 'fork #1 failed: %d (%s)' % (error.errno, error.strerror)
        os._exit(1)

    # it separates the son from the father
    os.chdir('/')
    os.setsid()
    os.umask(0)

    # create - fork 2
    try:
        pid = os.fork()
        if pid > 0:
            print 'Daemon PID %d' % pid
            os._exit(0)
    except OSError, error:
        print 'fork #2 failed: %d (%s)' % (error.errno, error.strerror)
        os._exit(1)

    functionDaemon()

def functionDaemon():
    logfile = dict(configFile.items('log'))
    zbxservice = dict(configFile.items('zbxservice'))
    zbxhost = dict(configFile.items('zbxhost'))
    zbxsender = dict(configFile.items('zbxsender'))
    log = Logger(logfile['logfile'], logging.DEBUG)

    while True:
        log.info('Begin check zbx service.')
        zbx = CheckZabbixServer(zbxservice['serviceip'], zbxservice['gateway'], zbxsender['hostname'], zbxsender['key'], zbxsender['value'])

        # 如果无法PING通网关，有可能 manager 服务器本身有问题
        fpinggateway = zbx.fpinggateway()
        if not fpinggateway:
            log.error('Ping gateway status is [fail]')
            time.sleep(30)
            continue
        else:
            log.info('Ping gateway status is [ok]')

        # 检测 masterhost 和 slavemaster 是否可以SSH
        # log.info('Check master and slave ssh connection.')
        try:
            if bool(zbxhost['pwd']):
                masterconn = ssh(zbxhost['masterhost'], int(zbxhost['port']), zbxhost['user'], password=zbxhost['pwd'])
            else:
                masterconn = ssh(zbxhost['masterhost'], int(zbxhost['port']), zbxhost['user'], key_filename=zbxhost['sshkey'])
        except:
            masterconn = False

        try:
            if bool(zbxhost['pwd']):
                slaveconn = ssh(zbxhost['slavehost'], int(zbxhost['port']), zbxhost['user'], password=zbxhost['pwd'])
            else:
                slaveconn = ssh(zbxhost['slavehost'], int(zbxhost['port']), zbxhost['user'], key_filename=zbxhost['sshkey'])
        except:
            slaveconn = False

        if masterconn and slaveconn:
            hoststatus = 'ok'
            log.info('master and slave ssh connection is [ok]')
            master_recovery = RecoveryZabbixServer(zbxservice['serviceip'], zbxservice['netmask'], zbxservice['device'], zbxservice['gateway'], masterconn)
            slave_recovery = RecoveryZabbixServer(zbxservice['serviceip'], zbxservice['netmask'], zbxservice['device'], zbxservice['gateway'], slaveconn)
        elif masterconn and not slaveconn:
            hoststatus = 'masterhost_ok'
            log.info('master ssh connection is [ok], but slave is [fail]')
            master_recovery = RecoveryZabbixServer(zbxservice['serviceip'], zbxservice['netmask'], zbxservice['device'], zbxservice['gateway'], masterconn)
        elif slaveconn and not masterconn:
            hoststatus = 'slavehost_ok'
            log.info('salve ssh connection is [ok], but master is [ok]')
            slave_recovery = RecoveryZabbixServer(zbxservice['serviceip'], zbxservice['netmask'], zbxservice['device'], zbxservice['gateway'], slaveconn)
        else:
            log.error('master and slave ssh connection is [fail]. please check the config')
            time.sleep(30)
            continue

        # 检测 zbx 的虚 IP 、服务状态
        fpingzbx = zbx.fpingzbx()
        if fpingzbx:
            log.info('Ping zbx service ip status is [ok]')
            zabbix_sender = zbx.zabbix_sender()
            if zabbix_sender:
                log.info('check zbx sender status is [ok]')
                zbxstatus = 'ip_ok_zbx_ok'
            else:
                log.info('check zbx sender status is [fail]')
                zbxstatus = 'ip_ok_zbx_fail'
        else:
            log.info('Ping zbx service ip status is [fail]')
            zbxstatus = 'ip_fail'

        # 如果虚 IP 不存在，则初始化 zbx
        if zbxstatus == 'ip_fail':
            if hoststatus == 'ok':
                log.info('master and slave ok, begin init zbx ha. please waiting...')
                if master_recovery.checkzbx():
                    master_recovery.stopzbx()
                if slave_recovery.checkzbx():
                    slave_recovery.stopzbx()
                master_recovery.addip()
                master_recovery.startzbx()
                if master_recovery.checkip() and master_recovery.checkzbx():
                    log.info('zbx init done, check status is [ok]')
                else:
                    log.info('zbx init done, but check status is [fail]')
            if hoststatus == 'masterhost_ok':
                if master_recovery.checkzbx():
                    master_recovery.stopzbx()
                log.info('master ok and slave fail, begin start zbx on master. please waiting...')
                master_recovery.addip()
                master_recovery.startzbx()
                if master_recovery.checkip() and master_recovery.checkzbx():
                    log.info('zbx start on master done, check status is [ok]')
                else:
                    log.info('zbx start on master done, but check status is [fail]')
            if hoststatus == 'slavehost_ok':
                if slave_recovery.checkzbx():
                    slave_recovery.stopzbx()
                log.info('master fail and slave ok, begin start zbx on slave.')
                slave_recovery.addip()
                slave_recovery.startzbx()
                if slave_recovery.checkip() and slave_recovery.checkzbx():
                    log.info('zbx start on slave done, check status is [ok]')
                else:
                    log.info('zbx start on slave done, but check status is [fail]')

        # 如果虚 IP 存在，但服务 fail，则重启服务
        if zbxstatus == 'ip_ok_zbx_fail':
            if hoststatus == 'ok':
                log.info('master and slave ok,begin start zbx server on masterhost. please waiting...')
                if master_recovery.checkip():
                    master_recovery.startzbx()
                if slave_recovery.checkip():
                    slave_recovery.delip()
                    master_recovery.addip()
                    master_recovery.startzbx()
                if master_recovery.checkip() and master_recovery.checkzbx():
                    log.info('zbx start on master done, check status is [ok]')
                else:
                    log.info('zbx start on master done, but check status is [fail]')
            if hoststatus == 'masterhost_ok': # 如果只有 master 可连，则将虚 IP 及服务启用在 master 上
                log.info('master ok, begin start zbx server on masterhost. please waiting...')
                master_recovery.startzbx()
                if master_recovery.checkip() and master_recovery.checkzbx():
                    log.info('zbx start on master done, check status is [ok]')
                else:
                    log.info('zbx start on master done, but check status is [fail]')
            if hoststatus == 'slavehost_ok': # 如果只有 slave 可连，则将虚 IP 及服务启用在 slave 上
                log.info('slave ok, begin start zbx server on slavehost. please waiting...')
                slave_recovery.startzbx()
                if slave_recovery.checkip() and slave_recovery.checkzbx():
                    log.info('zbx start on slave done, check status is [ok]')
                else:
                    log.info('zbx start on slave done, but check status is [fail]')

        # 如果虚 IP 和服务都 ok，两台主机都可连接
        if zbxstatus == 'ip_ok_zbx_ok' and hoststatus == 'ok':
            if zbxhost['failback'] == 'true': # 如果设置抢占，则让 zbx 启用在 master 主机上
                if master_recovery.checkip() and master_recovery.checkzbx():
                    log.info('zbx server running the masterhost: %s' %(zbxhost['masterhost']))
                else:
                    log.info('zbx server running the slavehost, begin failback. please waiting...')
                    slave_recovery.stopzbx()
                    slave_recovery.delip()
                    master_recovery.addip()
                    master_recovery.startzbx()
                    if master_recovery.checkip() and master_recovery.checkzbx():
                        log.info('failback done, check status is [ok]')
                    else:
                        log.info('failback done, check status is [fail]')
            if zbxhost['failback'] == 'false': # 如果未设置抢占，则输出当前服务运行主机
                if master_recovery.checkip() and master_recovery.checkzbx():
                    log.info('zbx server running the masterhost: %s' %(zbxhost['masterhost']))
                elif slave_recovery.checkip() and slave_recovery.checkzbx():
                    log.info('zbx server running the slavehost: %s' %(zbxhost['slavehost']))

        # 清理现场，关闭所有的 SSH 连接
        if hoststatus == 'ok':
            masterconn.close()
            slaveconn.close()
        elif hoststatus == 'masterhost_ok':
            masterconn.close()
        elif hoststatus == 'slavehost_ok':
            slaveconn.close()
        log.info('check zbx server done.')
        log.info('')
        time.sleep(30)
        continue

if __name__ == '__main__':
    Usage= """
zabbix server high availability solutions, can be used to manage virtual IP and zabbix server process.
https://github.com/whmove/zbxHA
usage: zbxha [ -c <configfile> | --config=configfile ] [ -h | --help ]
"""
    try:
        opts, args = getopt.getopt(sys.argv[1:], 'hc:', ['help', 'config='])
    except:
        print(Usage)
        sys.exit(2)

    if len(opts) < 1:
        print(Usage)
        sys.exit(2)

    config = ''
    for op,value in opts:
        if op in ('-h', '--help'):
            print(Usage)
            sys.exit()
        elif op in ('-c', '--config'):
            config = value
        else:
            print(Usage)
            sys.exit(2)

    if os.path.isfile(config):
        configFile = ConfigParser.ConfigParser(allow_no_value=True)
        configFile.read(config)
        createDaemon()
    else:
        print('Not found config file: %s' %(config))
        sys.exit(2)
